apiVersion: v1
kind: Service
metadata:
  # creationTimestamp: "2021-08-23T11:07:26Z"
  name: nginx-deployment
  namespace: default
  resourceVersion: "40883"
  # uid: 9190ab75-d61c-4ff4-a3d1-0d293fa8d72e
spec:
  clusterIP: 10.103.15.174
  clusterIPs:
  - 10.103.15.174
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30442
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
